import React from 'react'
import img2 from './../img/solarwaterheaterFPC.png'
import img1 from './../img/solarwaterheaterETC.png'
export default function SolarwaterheaterETC() {
    return (
        <div>
            <div class="productsIntro pt-lg-5"><div class="pt-lg-5 text-white text-center pt-5 fw-bold" style={{ fontSize: '52px' }}>Products</div><div class="fs-6 text-white text-center d-md-flex align-items-center justify-content-center"><div class="px-2"><a class="text-white text-center" href="/">Home</a>&nbsp; &nbsp; <i class="fa-solid fa-angle-right"></i></div><div class="px-2"><a class="text-white text-center" href="/solarWaterHeater">Solar Water Heater</a> &nbsp; &nbsp; <i class="fa-solid fa-angle-right"></i></div><div class="px-2"> Solar Water Heater (ETC)</div></div></div>
            <div class="productBody row"><div class="col-lg-6 d-flex"><div class="productImg m-auto "><img class="w-100" id="productImage" alt="" src={img1} /></div></div><div class="col-lg-6 py-lg-4"><h1 class="fw-bold">Solar Water Heater (ETC)</h1><div class="fs-5"><p>An Evacuated Tube Collector (ETC) is a solar water heating system that is based on efficient solar collector technology. It uses conductive glass tubes to absorb heat from the sun, which is then transferred to the water or other circulating fluids.<br />An ETC consists of a number of glass tubes that are made of borosilicate or soda lime glass. These sealed glass tubes have copper rods within them that are thermally conductive. The glass tubes are supported by a frame and are arranged in a parallel pattern. Each tube is made up of a thick outer tube and a thin inner tube. The air between the inner and outer tubes is removed to create a vacuum. The name, “evacuated tube,” comes from this evacuation of air. The vacuum gives the system an insulating effect, making heat loss difficult. <br/>ETC solar water heaters are more modern and more efficient when compared to their peers because:<br/></p></div><hr class="w-25 text-muted bg-muted" /><div class="fs-5"><div class="my-lg-3"><span class="fw-bold">Catagory:</span> Solar Water Heater</div><div class="my-lg-3"><span class="fw-bold">Tags:</span> capacity, innovation, solar energy</div></div><div class="my-3 my-lg-3"><a class="text-white fw-bold px-3 py-2  getInquiry" href="/contact" style={{ backgroundColor: 'rgb(87, 179, 62)' }}>Get Inquiry</a></div></div></div>
            <div class="relatedProduct "><h2>Related Products</h2><div class="galleryRow"><div class="galleryColumn"><a class=" solarPanelCard  text-dark" href="/heaterFPC"><div class="relatedProductImg d-flex align-items-center justify-content-center"><img class="mx-5 my-3" src={img2} alt="" /></div><hr /><div class="fw-bold text-center p-2 py-3"><div class="fs-5">Solar Water Heater (FPC)</div></div></a></div></div></div>
        </div>
    )
}
